dashboard/urls.py
# Try and import from newer django installs, but fallback gracefully
try:
    from django.conf.urls import include, url
except ImportError:
    from django.conf.urls.defaults import include, url

from dashboard import views

urlpatterns = [
    url(r'^$', views.home, name='admin_home'),

    url(r'^settings/$', views.settings, name='admin_settings'),
    url(r'^settings/(?P<grp_name>[a-z]+)/$', views.settings, name='settings_grp'),

    url(r'^categories/$', views.categories, name='dashboard_categories'),
    url(r'^categories/new/$', views.category_edit),
    url(r'^categories/edit/(?P<slug>[a-z_]+)/$', views.category_edit, name='category_edit'),
    url(r'^categories/remove/(?P<slug>[a-z_]+)/$', views.category_remove),
    url(r'^categories/edit/(?P<slug>[a-z_]+)/photo/add/$', views.category_photo_add),
    url(r'^categories/edit/(?P<slug>[a-z_]+)/photo/remove/$', views.category_photo_remove),
    url(r'^categories/edit/(?P<slug>[a-z_]+)/photo/get/$', views.category_photo_get, name='category_photo_get'),
    url(r'^categories/edit/(?P<slug>[a-z_]+)/photo/set/$', views.category_photo_set),
    url(r'^categories/edit/(?P<slug>[a-z_]+)/photo/flip/$', views.category_photo_flip),
    url(r'^categories/ajax/$', views.category_ajax, name='category_ajax'),

    url(r'^pages/$', views.pages, name='dashboard_pages'),
    url(r'^pages/new/$', views.page_edit),
    url(r'^pages/edit/(?P<slug>[a-z_]+)/$', views.page_edit),
    url(r'^pages/remove/(?P<slug>[a-z_]+)/$', views.page_remove),

    url(r'^pictures/$', views.photos, name='dashboard_pictures'),
    url(r'^picture/edit/(?P<pid>\d+)/$', views.photo_edit, name='photo_edit'),
    url(r'^pictures/ajax/$', views.picture_ajax, name='picture_ajax'),
    url(r'^picture/thumbs/(?P<pid>\d+)/$', views.photo_thumbs, name='photo_thumbs'),
    url(r'^picture/thumbs/(?P<pid>\d+)/generate/$', views.photo_thumbs_generate,
        name='photo_thumbs_generate'),

    url(r'^sizes/$', views.sizes, name='dashboard_sizes'),
    url(r'^sizes/new/$', views.size_edit),
    url(r'^sizes/edit/(?P<sid>\d+)/$', views.size_edit),

    url(r'^users/$', views.users, name='dashboard_users'),
    url(r'^users/new/$', views.user_edit),
    url(r'^users/edit/(?P<uid>\d+)/$', views.user_edit),
    url(r'^users/pw/(?P<uid>\d+)/$', views.user_pw),

    url(r'^upload/$', views.upload),
    url(r'^views/$', views.views),
    url(r'^daily/$', views.daily),
    url(r'^actions/$', views.actions, name='dashboard_actions'),
    url(r'^actions/thumbnails/$', views.regenerate_thumbnails),
]

raspis/urls.py
try:
    from django.conf.urls import include, url
except ImportError:
    from django.conf.urls.defaults import include, urls

from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static

from raspis import feeds, views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^today/$', views.today),

    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, name="login"),
    url(r'^login/redirect/$', views.login_redirect, name="login_redirect"),
    url(r'^logout/$', logout, name="logout"),

    url(r'^feed/rss/$', feeds.photoFeed(), name='rss'),
    url(r'^feed/atom/$', feeds.photoAtomFeed(), name='atom'),

    url(r'^ajax/categories/$', views.ajax_categories),

    url(r'^c/(?P<slug>[a-z_]+)/$', views.category, name='category'),
    url(r'^c/(?P<slug>[a-z_]+)/gallery/$', views.category_gallery),
    url(r'^c/(?P<slug>[a-z_]+)/slideshow/$', views.category_slideshow, name='category_slideshow'),

    url(r'^p/(?P<slug>[a-z_]+)/$', views.page, name='page'),

    url(r'^original/(?P<pid>\d+)/$', views.original, name='original'),
    url(r'^pic/(?P<pid>\d+)/$', views.show, name='show'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
import os
import hashlib
import math
from os.path import basename, splitext, exists

try:
    from cStringIO import StringIO
except ImportError:
    from io import StringIO

from django.db import models
from django.db.models.signals import post_delete, post_save

from raspis.constants import YESNO


# Helper functions

# This is used to get the path to upload an image to. It sets the path based
# on the displayDate field, meaning every photo will be in it's own
# directory.


def photo_path(instance, filename):
    if not instance.displayDate:
        return 'unknown/%s' % filename
    dt = instance.displayDate.strftime("%Y/%m")
    return os.path.join('originals', dt, filename)

# This is used to get the path to upload a thumbnail into. The path is the
# same as that used for the main image, but this function is needed as the
# references are different.
def thumbnailPath(instance, filename):
    if not instance.photo or not instance.photo.img:
        return 'unknown/%s' % filename
    dt = instance.photo.displayDate.strftime("%Y/%m")
    return os.path.join('thumbnails', dt, filename)

class ThumbnailSize(models.Model):
    name = models.CharField(max_length = 30, unique=True)
    width = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0, blank = True)
    square = models.BooleanField(default = False, choices = YESNO)
    absolute = models.BooleanField(default = False, choices = YESNO)

    def __unicode__(self): return u'%s' % self.name

    @property
    def filename_name(self):
        return u'%s' % self.name.replace(" ", "_")

    @property
    def crop_required(self):
        if self.square or self.absolute:
            return True
        return False

    @property
    def longest(self):
        if self.square:
            return float(self.width)
        if self.width >= self.height:
            return float(self.width)
        return float(self.height)

    def make_crop(self, img_sz):
        if self.square:
            left = (img_sz[0] - self.width) / 2
            top = (img_sz[1] - self.width) / 2
            w = h = self.width
            return left, top, left + self.width, top + self.width
        if self.absolute:
            left = (img_sz[0] - self.width) / 2
            top = (img_sz[1] - self.height) / 2
            return left, top, left + self.width, top + self.height

class Photo(models.Model):
    title = models.CharField(max_length = 100, blank = True)
    date_added = models.DateTimeField(auto_now_add = True)
    date = models.DateField("Photo Date", editable = False, null = True)
    image = models.ImageField(upload_to = 'originals')
    md5 = models.CharField(max_length = 32, editable = False, blank = True)

#    category = models.ForeignKey('Category', blank = True, null = True)

    def __unicode__(self):
        if len(self.title):
            return u'%s' % self.title
        return self.image.name

    def make_thumbnails(self):
        ''' Generate all required thumbnails. Some additional logic to ensure
            we don't have duplicates.
            NB This removes the current thumbnail image, so any modifications
               made to the thumbnail will be lost.
        '''
        for sz in ThumbnailSize.objects.all():
            ck = self.thumbnail_set.filter(size = sz)
            if len(ck):
                if len(ck) > 1:
                    for t in ck[1:]:
                        t.delete()
                t = ck[0]
            else:
                t = Thumbnail(photo = self, size = sz)
                t.save()
            t.make_thumbnail()

    def get_thumbnail(self, name):
        t = self.thumbnail_set.filter(size__name = name)
        if len(t) == 1:
            return t[0]
        try:
            sz = ThumbnailSize.objects.get(name = name)
        except ThumbnailSize.DoesNotExist:
            return None
        t, ctd = self.thumbnail_set.get_or_create(photo = self, size = sz)
        t.make_thumbnail()
        return t

    @property
    def longest(self):
        if self.image:
            return float(max(self.image.width, self.image.height))
        return 0.0

    @property
    def shortest(self):
        if self.image:
            return float(min(self.image.width, self.image.height))
        return 0.0

    def update_md5(self):
        m = hashlib.md5()
        fH = open(self.image.path, 'rb')
        m.update(fH.read())
        fH.close()
        self.md5 = m.hexdigest()

    def record_view(self):
        c, ctd = PhotoCounter.objects.get_or_create(photo = self)
        c.views += 1
        c.save()

class Thumbnail(models.Model):
    photo = models.ForeignKey(Photo)
    size = models.ForeignKey(ThumbnailSize)
    img = models.ImageField(upload_to='thumbnails', null = True)

    def __unicode__(self):
        return u'%s [%d, %s]' % (self.photo.title, self.id, self.size.name)

    def get_new_size(self, sz):
        # if square, shortest must be at least the required dimension
        if self.size.square:
            ratio = float(self.size.width) / self.photo.shortest
        elif self.size.absolute:
            ratio = max((float(self.size.width) / self.photo.image.width),
                        (float(self.size.height) / self.photo.image.height))
        else:
            ratio = float(self.size.longest) / self.photo.longest
        if ratio > 1.0:
            ratio = 1.0
        w = math.ceil(ratio * sz[0])
        h = math.ceil(ratio * sz[1])
        return int(w), int(h)

    def make_thumbnail(self):
        from PIL import Image
        from django.core.files.uploadedfile import SimpleUploadedFile

        if self.img and exists(self.img.path):
            os.remove(self.img.path)

        orig = Image.open(self.photo.image.path)
        fName, ext = splitext(basename(self.photo.image.name))
        thumb_filename = '%s_%s%s' % (self.photo.id, self.size.filename_name, ext)

        new_sz = self.get_new_size(orig.size)
        orig.thumbnail(new_sz, Image.ANTIALIAS)

        if self.size.crop_required:
            cropped = self.size.make_crop(new_sz)
            orig = orig.crop(cropped)

        if ext.lower() in ['.jpeg', '.jpg']:
            DJANGO_TYPE = 'image/jpeg'
            PIL_TYPE = 'jpeg'
        elif ext.lower() in ['.png']:
            DJANGO_TYPE = 'image/png'
            PIL_TYPE = 'png'
        elif ext.lower() == '.gif':
            DJANGO_TYPE = 'image/gif'
            PIL_TYPE = 'gif'

        temp_handle = StringIO()
        orig.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)
        suf = SimpleUploadedFile(thumb_filename, temp_handle.read(),
                                 content_type=DJANGO_TYPE)
        self.img.save(thumb_filename, suf, save=True)
#        self.insert_copyright()

    def flip(self):
        from PIL import Image
        orig = Image.open(self.img.path)
        ni = orig.transpose(Image.FLIP_LEFT_RIGHT)
        ni.save(self.img.path)

"""
pyexiv2 is python 2.x only, so until a replacement can be found - don't do this!
    def insert_copyright(self):
        try:
            metadata = pyexiv2.ImageMetadata(self.img.path)
            metadata.read()
        except IOError:
            return
        try:
            cfg = ConfigItem.objects.get(group='settings', key='site_author')
            name = cfg.value or cfg.dflt
            # todo - copyright? year?
            copy = 'Copyright %s. All rights reserved.' % name
            metadata['Exif.Image.Copyright'] = copy
            metadata['Exif.Image.Artist'] = name
            metadata['Iptc.Application2.Copyright'] = [copy]
            metadata['Iptc.Application2.Byline'] = [name]
            metadata['Xmp.xmpRights.Marked'] = True
            metadata['Xmp.dc.creator'] = [name]
            metadata.write()
        except:
            pass
"""


def insert_required(verbosity):
    if verbosity > 0:
        print("Checking preloaded data...")
    rqd_sizes = { 'Category': [ 600, 400, False, True ],
                  'Small Square': [ 75, 0, True, False ],
                  'Square':   [ 150, 0, True, False ],
                  'Small': [ 150, 0, False, False ],
                  'Medium': [ 300, 0, False, False ],
                  'Large': [ 800, 0, False, False ],
                }
    for r in sorted(rqd_sizes.keys()):
        try:
            ck = ThumbnailSize.objects.get(name = r)
        except ThumbnailSize.DoesNotExist:
            data = rqd_sizes[r]
            if verbosity > 1:
                print("Inserting Thumbnail Size '%s'" % r)
            ts = ThumbnailSize(name=r, width=data[0], height=data[1],
                               square=data[2], absolute=data[3])
            ts.save()

def cleanFiles(sender, **kwargs):
    inst = kwargs.get('instance', None)
    if inst is None:
        return
    for field in sender._meta.get_fields():
        if isinstance(field, models.ImageField):
            f = getattr(inst, field.name)
            if not (f):
                continue
            m = inst.__class__._default_manager
            if os.path.exists(f.path) and not \
                m.filter(**{'%s__exact' % field.name: getattr(inst, field.name)})\
                .exclude(pk=inst._get_pk_val()):
                os.remove(f.path)

def updateThumbnails(sender, **kwargs):
    inst = kwargs.get('instance', None)
    if not inst:
        return

    # update existing thumbnails...
    for t in Thumbnail.objects.filter(size = inst):
        t.make_thumbnail()

    if kwargs.get('created', False):
        # Just created, so add thumbnail size for existing photos
        for p in Photo.objects.all():
            t = Thumbnail(photo=p, size=inst)
            t.make_thumbnail()

def update_photo(sender, **kwargs):
    inst = kwargs.get('instance', None)
    if not inst:
        return
    inst.make_thumbnails()
    # set date here

post_delete.connect(cleanFiles, sender=Photo, dispatch_uid="PhotoRemove")

raspis/models.py
from django.db import models
from photo.models import Thumbnail, Photo
from raspis.constants import YESNO


class Category(models.Model):
    name = models.CharField('Name', max_length=30)
    slug = models.SlugField(editable=False)
    desc = models.CharField('Description', max_length=250, blank=True)
    visible = models.BooleanField('Is this category visible?', default=True, choices=YESNO)

    image = models.ForeignKey(Thumbnail, null=True, blank=True, editable=False)

    photos = models.ManyToManyField(Photo)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __unicode__(self): return u'%s' % self.name

    def save(self, *args, **kwargs):
        if self.image is None and self.photo_set.count():
            self.image = self.photo_set.all()[0].get_thumbnail('Category')
        super(Category, self).save(*args, **kwargs)

    @property
    def photo(self):
        if self.image is None:
            return None
        return self.image.photo

    def set_image(self, photo = None):
        if self.photos.count() == 0:
            self.image = None
            self.save()
            return

        if photo is None and self.image is None:
            photo = self.photos.all()[0]
        if photo:
            self.image = photo.get_thumbnail('Category')
            self.save()

    def add_photo(self, photo):
        self.photos.add(photo)
        self.set_image()

    def remove_photo(self, photo):
        if self.image and self.image.photo == photo:
            self.image = None
            self.save()
        self.photos.remove(photo)
        self.set_image()

    def save(self, *args, **kwargs):
        self.slug = self.name.lower().replace(' ', '_')
        super(Category, self).save(*args, **kwargs)

    def as_dict(self):
        d = {'name': self.name, 'slug': self.slug, 'desc': self.desc}
        if self.image and self.image.img:
            d['image'] = {'url': self.image.img.url,
                          'width': self.image.img.width,
                          'height': self.image.img.height}
        return d

    def flip_image(self):
        if self.image:
            self.image.flip()
            self.image.photo.get_thumbnail('Small').flip()

    def record_view(self):
        c, ctd = CategoryCounter.objects.get_or_create(category = self)
        c.views += 1
        c.save()

class Page(models.Model):
    title = models.CharField(max_length = 50)
    slug = models.SlugField(editable = False)
    url = models.URLField('External Link',max_length = 300, blank = True)
    content = models.TextField(blank = True)
    first_dt = models.DateField("First date to be displayed", null = True, blank = True)
    last_dt = models.DateField("Last date to be displayed", null = True, blank = True)

    def __unicode__(self):
        return u'Page: %s' % self.title

    def save(self, *args, **kwargs):
        self.slug = self.title.lower().replace(' ', '_')
        super(Page, self).save(*args, **kwargs)

class PhotoCounter(models.Model):
    photo = models.ForeignKey(Photo)
    views = models.PositiveIntegerField(default = 0)

    def __unicode__(self):
        return "%d views of %s" % (self.views, self.photo.title)

class CategoryCounter(models.Model):
    category = models.ForeignKey(Category)
    views = models.PositiveIntegerField(default = 0)

    def __unicode__(self):
        return "%d views of %s" % (self.views, self.category.name)

class DailyPhoto(models.Model):
    dt = models.DateField(unique=True)
    photo = models.ForeignKey(Photo)

    class Meta:
        ordering = ['-dt']

    def __unicode__(self):
        return "Daily photo for %s : %s" % (self.dt.strftime("%d %b %Y"), self.photo.title)

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Administration for {{ site_name }} : {% block page_title %}Dashboard{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/dashboard.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/smoothness/jquery-ui-1.8.20.custom.css" />

<!--[if !IE 7]>
	<style type="text/css">
		#wrap {display:table;height:100%}
	</style>
<![endif]-->
{% block extrahead %}{% endblock %}
    <style>
{% block extrastyle %}{% endblock %}
    </style>
  </head>
  <body>
    <div id="wrap">
    <header>
      <h1><a href="/">{{ site_name }}</a></h1>
    </header>
    
    <nav>
      <ul>
<li data-href="/dashboard/" {% if where = 'home' %}class="active"{% endif %}>Home</li>
<li data-href="settings" {% if where = 'settings' %}class="active"{% endif %}>Settings</li>
<li data-href="users" {% if where = 'users' %}class="active"{% endif %}>Users</li>
<li data-href="categories" {% if where = 'categories' %}class="active"{% endif %}>Categories</li>
<li data-href="sizes" {% if where = 'sizes' %}class="active"{% endif %}>Picture Sizes</li>
<li data-href="pages" {% if where = 'pages' %}class="active"{% endif %}>Pages</li>
<li data-href="pictures" {% if where = 'pictures' %}class="active"{% endif %}>Pictures</li>
<li data-href="upload" {% if where = 'upload' %}class="active"{% endif %}>Upload Pictures</li>
<li data-href="daily" {% if where = 'daily' %}class="active"{% endif %}>Daily Picture</li>
<li data-href="views" {% if where = 'views' %}class="active"{% endif %}>Views</li>
<li data-href="actions" {% if where = 'actions' %}class="active"{% endif %}>Actions</li>
{% if user.is_superuser %}
<li data-href="/admin/">Django Admin</li>
{% endif %}
<li data-href="/logout/">Logout</li>
      </ul>
    </nav>

    <div id="content">
{% if messages %}
  <div id="messages">
    {% for m in messages %}{{m}}{% endfor %}
  </div>
{% endif %}
{% block content %}
{% endblock %}
    </div>
    </div>
    <footer>
      <p>{{ copyright|safe }} {{ site_author }}</p>
    </footer>
{% if debug %}
    <script src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"> </script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.8.20.custom.min.js"> </script>
{% else %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
{% endif %}
    <script>
$('nav>ul>li').click(function() {
  var href = $(this).attr('data-href');
  if (href.substring(0,1) == '/') {
    window.location.href = href;
  } else {
    window.location.href = '/dashboard/' + href + '/'; 
  }
});
$('.aButton').button();
{% if messages %}
$('#messages').delay(7500).slideUp('slow', function() { $('#messages').remove(); });
{% endif %}
{% block extrascript %}{% endblock %}
    </script>
  </body>
</html>

dashboard/templates/dashboard/categories.html
{% extends 'dashboard/base.html' %}

{% load images %}

{% block page_title %}Settings for {{ site_name }} : Dashboard{% endblock %}

{% block content %}
<header>
  <h1>Categories</h1>
  <p>Create & manage the categories photos will be assigned to.</p>
</header>

<table width="80%">
  <tr>
    <th width="20%">Category Name</th>
    <th width="50%">Description</th>
    <th width="10%"># Photos</th>
    <th width="10%">Visible?</th>
    <th width="10%">Options</th>
  </tr>
{% for c in cats %}
  <tr>
    <td><a href="edit/{{c.slug}}/">{{c.name}}</a></td>
    <td><span class="italic">{{ c.desc}}</span></td>
    <td class="centered">{{c.photo_set.count}}</td>
    <td class="centered">{{ c.visible }}</td>
    <td class="centered"><a href="remove/{{c.slug}}/" class="aButton remove" alt="Remove" title="Remove">X</a></td>
  </tr>
{% endfor %}
</table>
<p><a href="new/" class="aButton">Add Category</a></p>


{% endblock %}

{% block extrascript %}
$('.remove').click(function(ev) {
  var name = $(this).parent().siblings().eq(0).text();
  if (! confirm("Please confirm you wish to remove the category " + name + "?")) {
    ev.preventDefault();
  }
});
{% endblock %}

dashboard/templates/dashboard/category_edit.html
{% extends 'dashboard/base.html' %}

{% load images %}

{% block page_title %}{% if cat %}Edit '{{cat.name}}' Category{% else %}Add New Category{% endif %}{% endblock %}

{% block extrastyle %}
form label, form input[type='text'] { font-size: 14pt; }
#flip { position: absolute; bottom: 3px; left: 3px; }
{% endblock %}

{% block content %}
<header>
  <h1>{% if cat %}Edit '{{cat.name}}' Category{% else %}Add New Category{% endif %}</h1>
</header>

<table width="100%">
  <tr>
    <td width="20%" align="center" vertical-align="middle" id="catpicture" style="position: relative;">
{% if cat.image %}
        {% getImageTag cat.image %}
        <span id="flip">flip</span>
{%else %}
        <p>Drop an image here to set the category picture</p>
{%endif%}
    </td>

    <td width="80%">
        <form action="." method="POST">{% csrf_token %}
            {{ form.as_p }}
            <p>
                <input type="submit" class="aButton" value="{% if cat %}Update{% else %}Create{% endif %}"/>
            </p>
        </form>
    </td>
  </tr>
</table>

{% if cat %}
<section id="drop_add">
    <header><h1>Photos Included</h1></header>
    <div id="included">
    {% for p in pics %}{% getImageTag p "Square" %}{% empty %}<p>No photos included at present.</p>{% endfor %}
    </div>
</section>

<section id="drop_remove">
  <header><h1>Photos Available To Include</h1></header>
<div id="avail">
{% for p in avail %}
    {% getImageTag p "Square" %}
{% empty %}
    <p>No photos available to be include.</p>
{% endfor %}
</div>
</section>
<div id="spinner" class="round10">
  <img src="{{STATIC_URL}}css/ajax-loader2.gif" align="center"/>
  <p>Submitting...</p>
</div>

{% endif %}

{% endblock %}

{% block extrascript %}
options = { opacity: 0.7, revert: true };
$("#avail>img").draggable(options);
$("#included>img").draggable(options);
function move_element(el, to)
{
    el.fadeOut(function() {
      el.remove().css({'top': null, 'left': null, 'opacity': 1.0});
      el.remove().appendTo(to).fadeIn().draggable(options);
    });
}
$("#drop_add").droppable({
  drop: function( event, ui ) {
    $('#spinner').show();
    var el = ui.draggable;
    $.ajax({url: 'photo/add/', type: 'post',
            data: {'id': el.attr('data-id')},
            success: function() { move_element(el, $('#included')); },
            complete: function() { $('#spinner').hide(); }
           });

  }
});
$("#drop_remove").droppable({
  drop: function( event, ui ) {
    $('#spinner').show();
    var el = ui.draggable;
    $.ajax({url: 'photo/remove/', type: 'post',
            data: {'id': el.attr('data-id')},
            success: function() { move_element(el, $('#avail')); },
            complete: function() { $('#spinner').hide(); }
           });
  }
});

$("#catpicture").droppable({
  drop: function(ev, ui) {
    var el = ui.draggable;
    $.ajax({url: 'photo/set/', type: 'post',
            data: {'id': el.attr('data-id')},
            success: get_picture
           });
  }
});
{%if cat %}
function get_picture() {
  $('#catpicture').find('img').remove();
  $('#catpicture>p').show();
  $.ajax({url: '{% url 'category_photo_get' cat.slug %}',
          dataType: 'json',
          success: function(data) {
console.log(data);
            if (data.url) {
              $('#catpicture>p').hide();
              url = data.url + '?lastmod=' + new Date().getTime();
              $('<img>').attr({'src': url}).width(data.width).height(data.height).appendTo($('#catpicture'));
            }
          }
  });
}
{%endif%}
$('#flip').click(function() {
  $.ajax({url: 'photo/flip/',
          success: function() {
            $('#catpicture>img').remove();
            get_picture();
          }
         });
});
get_picture();
{% endblock %}

dashboard/templates/dashboard/daily.html
{% extends 'dashboard/base.html' %}

{% load images %}

{% block page_title %}Daily Pictures{% endblock %}

{% block extrastyle %}
{% endblock %}

{% block content %}
<header>
  <h1>Daily Pictures</h1>
  <p>The pictures chosen to be the picture of the day, past, present and future.</p>
</header>

<section>
  <header><h1>Past</h1></header>
  <p class="centered">
  {% for p in past %}
    {% getImageTag p.photo "Square" %}
  {% endfor %}
  </p>
</section>

<section>
  <header><h1>Today</h1></header>
  <p class="centered">
  {% if present %}{% getImageTag present.photo "Medium" %}{% else %}No image selected for today.{% endif %}
  </p>
</section>

<section>
  <header><h1>Upcoming</h1></header>
  <p class="centered">
  {% for p in future %}
    {% getImageTag p.photo "Square" %}
  {% endfor %}
  </p>
</section>
  
{% endblock %}

dashboard/templates/dashboard/page_edit.html
{% extends 'dashboard/base.html' %}

{% load images %}

{% block page_title %}{% if page %}Edit '{{page.title}}' Page{% else %}Add New Page{% endif %}{% endblock %}

{% block content %}
<header>
  <h1>{% if page %}Edit '{{page.title}}' Page{% else %}Add New Page{% endif %}</h1>
</header>

<form action="." method="POST">{% csrf_token %}
{{ form.as_p }}
<p><input type="submit" class="aButton" value="{% if page %}Update{% else %}Create{% endif %}"/></p>
</form>
{% endblock %}

{% block extrascript %}
$('#id_first_dt').datepicker();
$('#id_last_dt').datepicker();
{% endblock %}